### ISSUE TITLE
What this?

### ISSUE THREAD

**Issue by kolkov** [sevlyar/go-daemon#11]
Try to get from github:

```
D:\Go\src\inframe>go get github.com/sevlyar/go-daemon
# github.com/sevlyar/go-daemon
..\github.com\sevlyar\go-daemon\daemon_posix.go:51: undefined: syscall.Credential
```

**Comment by sevlyar** [comment]
Give me an information about your environment:
`go env`
`go version`

**Comment by Huong-nt** [comment]
I have same issue
`e:\Work\Miraway\GoWorkspace\src>go env
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=E:\Work\Miraway\GoWorkspace
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1`
`e:\Work\Miraway\GoWorkspace\src>go version
go version go1.7 windows/amd64`

**Comment by Kulak** [comment]
I think it is clear that issue is on Windows.  I kind of makes sense.  Windows has no daemons.  Only Linux, FreeBSD and Mac OS X.

Given that we only have posix implementation, it is safe to say that windows is not supported.  It would be nice to be clear about it in readme, but that's about it.

**Comment by sevlyar** [comment]
@Kulak, You are right. @kolkov, @Huong-nt Windows is not supported because it has its own services system. But the library should be properly compiled for Windows now and you can build a cross-platform application by using go-deamon for *nix and some another library for Windows.
