### ISSUE TITLE
go-daemon does not remove the pidfile on exit

### ISSUE THREAD

**Issue by abligh** [sevlyar/go-daemon#12]
`go-daemon` does not remove its pidfile even on a clean stop. This can be seen with the sample application. This is a bit odd as `daemon-posix.go` has:

```
// Release provides correct pid-file release in daemon.
func (d *Context) Release() (err error) {
    if !initialized {
        return
    }
    if d.pidFile != nil {
        err = d.pidFile.Remove()
    }
    return
}
```

and `Release()` is definitely being called, with `d.PidFile` non-null.

I'm running OS-X, with today's master. Here's a demo. Note the file `pid` is not deleted.

```
nimrod:sample amb$ go build
nimrod:sample amb$ ./sample
nimrod:sample amb$ ps -ef | fgrep sample
  501 22111     1   0  6:34pm ??         0:00.00 [go-daemon sample]
  501 22116 22094   0  6:34pm ttys021    0:00.00 fgrep sample
nimrod:sample amb$ cat pid
22111                                                         # linebreak inserted for ease of reading
nimrod:sample amb$ ./sample -s stop
nimrod:sample amb$ ps -ef | fgrep sample
  501 22123 22094   0  6:35pm ttys021    0:00.00 fgrep sample
nimrod:sample amb$ cat pid
22111                                                         # linebreak inserted for ease of reading
nimrod:sample amb$
```

**Comment by sevlyar** [comment]
Bug is reproduced for OS X. @abligh, thank you for the report.

**Comment by bfrancojr** [comment]
Hi,

I'm facing similar issue under OSX. Error like:

```
lstat /proc/self/fd/4: no such file or directory
```

and no pid file was removed.

I've patched the Remove function at lock_file.go line 101 to:

```go
// Remove removes lock, closes and removes an open file.
func (file *LockFile) Remove() error {
        defer file.Close()

        if err := file.Unlock(); err != nil {
                return err
        }

        return syscall.Unlink(file.Name())
}
```

It solved my problem under OSX but I'm not sure though if it would work in other platforms in the same way.

**Comment by abligh** [comment]
@bfrancojr I presume the reason the author did not use that method is because it would break under `chroot` conditions (as the file name changes), hence my `getFdName()` based fix.

**Comment by bfrancojr** [comment]
I see. Makes sense.
Thanks a lot for the explanation!
