### ISSUE TITLE
Documentation and/or tutorial ?

### ISSUE THREAD

**Issue by Depado** [sevlyar/go-daemon#14]
Hello,
I'm really interested in your project, it looks really great. Is there a way you could provide some more documentation or other examples ? 

Thanks a lot in advance, and thanks for your amazing project :D

**Comment by sevlyar** [comment]
Thank you. I have added some [examples](https://github.com/sevlyar/go-daemon/tree/master/examples/cmd).

Please suggest what kind of example you want (separate issue for every example) and i will implement most popular.

**Comment by Depado** [comment]
Thanks a lot 😄 
This will help me ! 🎆
