### ISSUE TITLE
chroot value clarification

### ISSUE THREAD

**Issue by Kulak** [sevlyar/go-daemon#15]
// If Chroot is non-empty, the child changes root directory
Chroot string

Are we talking about standard unix chroot functionality in here?

high level

https://www.freebsd.org/cgi/man.cgi?chroot(8)

and system call level:

https://www.freebsd.org/cgi/man.cgi?query=chroot&sektion=2&apropos=0&manpath=FreeBSD+10.3-RELEASE+and+Ports

Thank you

**Comment by sevlyar** [comment]
System call level: [syscall.Chroot](https://golang.org/src/syscall/zsyscall_linux_amd64.go?s=6833:6869#L269)

**Comment by Kulak** [comment]
thank you
