### ISSUE TITLE
Remove pid file failed, if pid file name is longer than 64 on Linux

### ISSUE THREAD

**Issue by jiedo** [sevlyar/go-daemon#16]
Hi, 

I find a problem, the pid file is left over after program exit . I check the code and find the file name  is truncated.

```
syscall.Unlink(name) 
```

The size of symbolic link file in /proc is always 64, this buf may not longer enough.

```
    if fi, err = os.Lstat(path); err != nil {
        return
    }
    buf := make([]byte, fi.Size()+1)

    if n, err = syscall.Readlink(path, buf); err == nil {
        name = string(buf[:n])
    }
```

Thanks!

**Comment by sevlyar** [comment]
Many thanks for the report!
