### ISSUE TITLE
Passing flags to worker.

### ISSUE THREAD

**Issue by drawks** [sevlyar/go-daemon#2]
Try as I might I cannot understand how a commandline flag can be passed to the daemonized worker process. Perhaps a more detailed sample including some comments is in order?

**Comment by sevlyar** [comment]
Context.Args field is used for passing command-line arguments to the demon. Just keep in mind that in the posix-systems, the first argument is the name of the command.

Samples:
```go
// os.Args will be used
daemon.Context{
    Args: nil,
}
// Custom parameters will be passed
daemon.Context{
    Args: []string{"[go-daemon sample]", "--help"},
}
```
"man exec":
> ...
>The  const  char *arg and subsequent ellipses in the execl(), execlp(),
> and execle() functions can be thought of  as  arg0,  arg1,  ...,  argn.
> Together  they  describe  a list of one or more pointers to null-termi‐
> nated strings that represent the argument list available  to  the  exe‐
> cuted  program.  The first argument, by convention, should point to the
> filename associated with the file being executed. ...
