### ISSUE TITLE
OSX isn't supported but claimed

### ISSUE THREAD

**Issue by leprosus** [sevlyar/go-daemon#20]
Please release OSX support

$ cd ~ /go/src/github.com/sevlyar/go-daemon
$ uname -a && go test
Darwin mac.local 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64
signal: killed
FAIL	github.com/sevlyar/go-daemon	0.006s

**Comment by sevlyar** [comment]
Many thanks for the report!
