### ISSUE TITLE
Using `os.Args` includes the process bin name

### ISSUE THREAD

**Issue by timfallmk** [sevlyar/go-daemon#34]
From [the comment](https://github.com/sevlyar/go-daemon/blob/master/daemon.go#L44):

```
// If Args is non-nil, it gives the command-line args for the
// daemon-process. If it is nil, the result of os.Args will be used
// (without program name).
```

This is not strictly true. [`prepareEnv`](https://github.com/sevlyar/go-daemon/blob/master/daemon_unix.go#L125), in the case no `Args` passed, sets the `Args` equal to `os.Arg` which _includes_ the process name. Changing this to the following would fix it.

```golang
d.Args = os.Args[1:]
```

I suspect this is related to #33

**Comment by sevlyar** [comment]
Thank you for the report, @timfallmk 
I will fix documentation.
