### ISSUE TITLE
Need for an example (fork-trick)

### ISSUE THREAD

**Issue by sttyru** [sevlyar/go-daemon#42]
Hello!

**Thanks for awesome package!** Can I ask you for share of an detailed example with the implementation of "fork-trick"? I'm writing yet another HTTP-server and I need to run listener from another user and group. I'd found of your explanation but I haven't enough expirience in Golang for writing of the ready-for-use code. 

Thanks for advice!

**Comment by sevlyar** [comment]
Hello @sttyru, please see the example: https://github.com/sevlyar/go-daemon/blob/master/examples/cmd/gd-simple/simple.go
