### ISSUE TITLE
New release needed

### ISSUE THREAD

**Issue by ncw** [sevlyar/go-daemon#43]
Can you make a new release please?

I'm having to carry over a pin to master to get the lock_file fixes for macOS.

https://github.com/ncw/rclone/blob/41f709e13b6b2be65b6a80357c932a1da28a10c7/Gopkg.toml#L1-L5

Thanks :-)

Nick

**Comment by sevlyar** [comment]
Thank you for the request.

https://github.com/sevlyar/go-daemon/tree/v0.1.4

**Comment by ncw** [comment]
Thank you very much :-)
