### ISSUE TITLE
Reopening logfile

### ISSUE THREAD

**Issue by corpix** [sevlyar/go-daemon#7]
Is there any way to reopen logfile when some event occured?

**Comment by sevlyar** [comment]
Give me more information please.

**Comment by corpix** [comment]
There is [LogFileName](https://github.com/sevlyar/go-daemon/blob/master/daemon_posix.go#L30) field in the `Context` struct.
Lets suppose I want my daemon to write a log file `app.log`.
I also want my logfile to be rotated with usual Linux tools(logrotate) at some point of time.
Currently there is no way to tell the daemon that application log file should be reopened(recreated in this case).
I think there should be some public API to recreate the log file externaly to allow users implement their custom logic(e.g. by signal or then some other event occurs).

**Comment by sevlyar** [comment]
There are several ways to support of log rotation. One of them:
You can implement handler of any suitable signal (for example SIGHUP) as shown in the [example](https://godoc.org/github.com/sevlyar/go-daemon#example-package). The handler must close `os.Stderr` and reopen a logfile when executed. Utility `logrotate` with correct settings will send correct signal to the daemon after the log rotation.
Or you can use [file system notifications](https://godoc.org/gopkg.in/fsnotify.v1) to track the renaming of the log file.

**Comment by corpix** [comment]
Yes, but is there any way to alter internal `Context`'s [logFile](https://github.com/sevlyar/go-daemon/blob/master/daemon_posix.go#L57) field to support this?

**Comment by sevlyar** [comment]
In child's process this field not initialized and not used: https://github.com/sevlyar/go-daemon/blob/master/daemon_posix.go#L221. The log file available over the descriptor of file `#2` and lib file `os.Stderr`. The parent's process passes the opened log file descriptor as `#2` to the child's process on the startup. And the library wraps the descriptor in struct `os.File (os.Stderr)`. You can manipulate the log file by using this variable.

**Comment by Maksadbek** [comment]
I encountered the same problem, I could not change the as it is not imported

**Comment by sevlyar** [comment]
Please see [Log Rotation](https://github.com/sevlyar/go-daemon/tree/master/examples/cmd/gd-log-rotation) example for the reference.
