### ISSUE TITLE
Is there a new version release plan? 

### ISSUE THREAD

**Issue by LilyAndLily** [sevlyar/go-daemon#83]
Hey, we want a stable and suitable version that can be used in the production environment. But I found that it has been a long time since the last version was released(v0.1.5). Will the project be continuously updated with new versions? Is there a new version release plan?

**Comment by neujie** [comment]
@sevlyar the version is long time no release, when to release the new version?

**Comment by deniszh** [comment]
hi @LilyAndLily 
I can make release

**Comment by deniszh** [comment]
Done - https://github.com/sevlyar/go-daemon/releases/tag/v0.1.6
