### ISSUE TITLE
Maintanence

### ISSUE THREAD

**Issue by synackSA** [sevlyar/go-daemon#89]
Is this package still maintained? I see open Pull requests that are pretty old and the code hasn't had a commit in close to a year now. I don't want to implement a package that isn't being maintained anymore.

**Comment by deniszh** [comment]
@synackSA : Are you missing some specific PR? I see only #86, which is 3 month old and missed smh, should be merged.

**Comment by synackSA** [comment]
It was just that one, but was wondering why there's been no changes to the repo in about a year. If you're in a stable position and you don't have anything else planned, are you planning on pushing v1.0 ?

**Comment by dmitris** [comment]
could you merge https://github.com/sevlyar/go-daemon/pull/65 which adds a `go.mod` file - or would you prefer a separate PR with only the `go.mod` / `go.sum` files? I'd be happy to raise one.

**Comment by deniszh** [comment]
@dmitris : merged

**Comment by mozhuli** [comment]
@deniszh Is there have a plan to release v1.0 or v0.1.7？

**Comment by deniszh** [comment]
Sure, can do v0.1.7
